dist: xenial

language: go
cache: false

env:
  - GO111MODULE=on

go:
  - 1.15

install: true

notifications:
  email: false

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run
  - make test

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - git fetch --prune --all
  - bash <(curl -Ls https://raw.githubusercontent.com/josemiguelmelo/next-git-version/master/generate.sh) v > VERSION
  - export TRAVIS_TAG=$(cat VERSION)
  - git tag $TRAVIS_TAG $TRAVIS_COMMIT
  
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  overwrite: true
  skip_cleanup: true
